/** @category Icons */
import activity from './svgs/activity.svg';
import add from './svgs/add.svg';
import arrowDown from './svgs/arrow-down.svg';
import arrowLeft from './svgs/arrow-left.svg';
import arrowRight from './svgs/arrow-right.svg';
import arrowUp from './svgs/arrow-up.svg';
import baby from './svgs/baby.svg';
import calendarHeatMap from './svgs/calendar--heat-map.svg';
import calendar from './svgs/calendar.svg';
import caretDown from './svgs/caret-down.svg';
import caretLeft from './svgs/caret-left.svg';
import caretRight from './svgs/caret-right.svg';
import caretUp from './svgs/caret-up.svg';
import chartAverage from './svgs/chart-average.svg';
import chartLine from './svgs/chart-line.svg';
import checkmarkFilled from './svgs/checkmark--filled.svg';
import checkmarkOutline from './svgs/checkmark--outline.svg';
import chemistry from './svgs/chemistry.svg';
import chevronDown from './svgs/chevron-down.svg';
import chevronLeft from './svgs/chevron-left.svg';
import chevronRight from './svgs/chevron-right.svg';
import chevronUp from './svgs/chevron-up.svg';
import close from './svgs/close.svg';
import closeFilled from './svgs/close--filled.svg';
import closeOutline from './svgs/close--outline.svg';
import document from './svgs/document.svg';
import documentAttachment from './svgs/document-attachment.svg';
import drugOrder from './svgs/drug-order.svg';
import download from './svgs/download.svg';
import edit from './svgs/edit.svg';
import eventSchedule from './svgs/event-schedule.svg';
import events from './svgs/events.svg';
import genderFemale from './svgs/gender-female.svg';
import genderMale from './svgs/gender-male.svg';
import genderOther from './svgs/gender-other.svg';
import genderUnknown from './svgs/gender-unknown.svg';
import genericOrderType from './svgs/generic-order-type.svg';
import group from './svgs/group.svg';
import groupAccess from './svgs/group-access.svg';
import hospitalBed from './svgs/hospital-bed.svg';
import imageMedical from './svgs/image-medical.svg';
import information from './svgs/information.svg';
import informationFilled from './svgs/information--filled.svg';
import informationSquare from './svgs/information--square.svg';
import inventoryManagement from './svgs/inventory-management.svg';
import labOrder from './svgs/lab-order.svg';
import listChecked from './svgs/list-checked.svg';
import location from './svgs/location.svg';
import materialOrder from './svgs/material-order.svg';
import maximize from './svgs/maximize.svg';
import medication from './svgs/medication.svg';
import messageQueue from './svgs/message-queue.svg';
import microscope from './svgs/microscope.svg';
import money from './svgs/money.svg';
import mother from './svgs/mother.svg';
import movement from './svgs/movement.svg';
import overflowMenuHorizonal from './svgs/overflow-menu--horizontal.svg';
import overflowMenuVertical from './svgs/overflow-menu--vertical.svg';
import password from './svgs/password.svg';
import pedestrianFamily from './svgs/pedestrian-family.svg';
import pen from './svgs/pen.svg';
import procedureOrder from './svgs/procedure-order.svg';
import printer from './svgs/printer.svg';
import programs from './svgs/programs.svg';
import renew from './svgs/renew.svg';
import referralOrder from './svgs/referral-order.svg';
import report from './svgs/report.svg';
import reset from './svgs/reset.svg';
import save from './svgs/save.svg';
import search from './svgs/search.svg';
import settings from './svgs/settings.svg';
import shoppingCart from './svgs/shopping-cart.svg';
import shoppingCartArrowDown from './svgs/shopping-cart--arrow-down.svg';
import stickyNoteAdd from './svgs/sticky-note-add.svg';
import switcher from './svgs/switcher.svg';
import syringe from './svgs/syringe.svg';
import tableOfContents from './svgs/table-of-contents.svg';
import table from './svgs/table.svg';
import time from './svgs/time.svg';
import tools from './svgs/tools.svg';
import translate from './svgs/translate.svg';
import trashCan from './svgs/trash-can.svg';
import treeViewAlt from './svgs/tree-view--alt.svg';
import userAvatar from './svgs/user-avatar.svg';
import userFollow from './svgs/user-follow.svg';
import userXray from './svgs/user-xray.svg';
import user from './svgs/user.svg';
import viewOff from './svgs/view-off.svg';
import view from './svgs/view.svg';
import warning from './svgs/warning.svg';
import { addSvg } from '../svg-utils';
import { type IconId } from './icons';

export function setupIcons() {
  addIconSvg('egen-icon-activity', activity);
  addIconSvg('egen-icon-add', add);
  addIconSvg('egen-icon-arrow-down', arrowDown);
  addIconSvg('egen-icon-arrow-left', arrowLeft);
  addIconSvg('egen-icon-arrow-right', arrowRight);
  addIconSvg('egen-icon-arrow-up', arrowUp);
  addIconSvg('egen-icon-baby', baby);
  addIconSvg('egen-icon-calendar-heat-map', calendarHeatMap);
  addIconSvg('egen-icon-calendar', calendar);
  addIconSvg('egen-icon-caret-down', caretDown);
  addIconSvg('egen-icon-caret-left', caretLeft);
  addIconSvg('egen-icon-caret-right', caretRight);
  addIconSvg('egen-icon-caret-up', caretUp);
  addIconSvg('egen-icon-chart-average', chartAverage);
  addIconSvg('egen-icon-chart-line', chartLine);
  addIconSvg('egen-icon-checkmark-filled', checkmarkFilled);
  addIconSvg('egen-icon-checkmark-outline', checkmarkOutline);
  addIconSvg('egen-icon-chemistry', chemistry);
  addIconSvg('egen-icon-chevron-down', chevronDown);
  addIconSvg('egen-icon-chevron-left', chevronLeft);
  addIconSvg('egen-icon-chevron-right', chevronRight);
  addIconSvg('egen-icon-chevron-up', chevronUp);
  addIconSvg('egen-icon-close', close);
  addIconSvg('egen-icon-close-filled', closeFilled);
  addIconSvg('egen-icon-close-outline', closeOutline);
  addIconSvg('egen-icon-document', document);
  addIconSvg('egen-icon-document-attachment', documentAttachment);
  addIconSvg('egen-icon-download', download);
  addIconSvg('egen-icon-drug-order', drugOrder);
  addIconSvg('egen-icon-edit', edit);
  addIconSvg('egen-icon-event-schedule', eventSchedule);
  addIconSvg('egen-icon-events', events);
  addIconSvg('egen-icon-gender-female', genderFemale);
  addIconSvg('egen-icon-gender-male', genderMale);
  addIconSvg('egen-icon-gender-other', genderOther);
  addIconSvg('egen-icon-gender-unknown', genderUnknown);
  addIconSvg('egen-icon-generic-order-type', genericOrderType);
  addIconSvg('egen-icon-group', group);
  addIconSvg('egen-icon-group-access', groupAccess);
  addIconSvg('egen-icon-hospital-bed', hospitalBed);
  addIconSvg('egen-icon-image-medical', imageMedical);
  addIconSvg('egen-icon-information', information);
  addIconSvg('egen-icon-information-filled', informationFilled);
  addIconSvg('egen-icon-information-square', informationSquare);
  addIconSvg('egen-icon-inventory-management', inventoryManagement);
  addIconSvg('egen-icon-lab-order', labOrder);
  addIconSvg('egen-icon-list-checked', listChecked);
  addIconSvg('egen-icon-location', location);
  addIconSvg('egen-icon-material-order', materialOrder);
  addIconSvg('egen-icon-maximize', maximize);
  addIconSvg('egen-icon-medication', medication);
  addIconSvg('egen-icon-message-queue', messageQueue);
  addIconSvg('egen-icon-microscope', microscope);
  addIconSvg('egen-icon-money', money);
  addIconSvg('egen-icon-mother', mother);
  addIconSvg('egen-icon-movement', movement);
  addIconSvg('egen-icon-overflow-menu--horizontal', overflowMenuHorizonal);
  addIconSvg('egen-icon-overflow-menu--vertical', overflowMenuVertical);
  addIconSvg('egen-icon-password', password);
  addIconSvg('egen-icon-pedestrian-family', pedestrianFamily);
  addIconSvg('egen-icon-pen', pen);
  addIconSvg('egen-icon-printer', printer);
  addIconSvg('egen-icon-procedure-order', procedureOrder);
  addIconSvg('egen-icon-programs', programs);
  addIconSvg('egen-icon-renew', renew);
  addIconSvg('egen-icon-referral-order', referralOrder);
  addIconSvg('egen-icon-report', report);
  addIconSvg('egen-icon-reset', reset);
  addIconSvg('egen-icon-save', save);
  addIconSvg('egen-icon-search', search);
  addIconSvg('egen-icon-settings', settings);
  addIconSvg('egen-icon-shopping-cart', shoppingCart);
  addIconSvg('egen-icon-shopping-cart--arrow-down', shoppingCartArrowDown);
  addIconSvg('egen-icon-sticky-note-add', stickyNoteAdd);
  addIconSvg('egen-icon-switcher', switcher);
  addIconSvg('egen-icon-syringe', syringe);
  addIconSvg('egen-icon-table-of-contents', tableOfContents);
  addIconSvg('egen-icon-table', table);
  addIconSvg('egen-icon-time', time);
  addIconSvg('egen-icon-tools', tools);
  addIconSvg('egen-icon-translate', translate);
  addIconSvg('egen-icon-trash-can', trashCan);
  addIconSvg('egen-icon-tree-view--alt', treeViewAlt);
  addIconSvg('egen-icon-user-avatar', userAvatar);
  addIconSvg('egen-icon-user-follow', userFollow);
  // userXray is also used for imaging orders
  addIconSvg('egen-icon-user-xray', userXray);
  addIconSvg('egen-icon-user', user);
  addIconSvg('egen-icon-view-off', viewOff);
  addIconSvg('egen-icon-view', view);
  addIconSvg('egen-icon-warning', warning);
}

/**
 * a type-safe wrapper around addSvg
 * @param iconId
 * @param svgString
 */
function addIconSvg(iconId: IconId, svgString: string) {
  addSvg(iconId, svgString);
}
